name: CI - Pipeline HTML/CSS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Verificar arquivos
        run: |
          if (Test-Path "index.html") { Write-Output "index.html encontrado" } else { throw "index.html não encontrado" }
          if (Test-Path "styles.css") { Write-Output "style.css encontrado" } else { throw "style.css não encontrado" }
